
export abstract class AppConstants {
  static readonly States = [
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
    { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
    { value: 'Assam', label: 'Assam' },
    { value: 'Bihar', label: 'Bihar' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh' },
    { value: 'Goa', label: 'Goa' },
    { value: 'Gujarat', label: 'Gujarat' },
    { value: 'Haryana', label: 'Haryana' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
    { value: 'Jharkhand', label: 'Jharkhand' },
    { value: 'Karnataka', label: 'Karnataka' },
    { value: 'Kerala', label: 'Kerala' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
    { value: 'Maharashtra', label: 'Maharashtra' },
    { value: 'Manipur', label: 'Manipur' },
    { value: 'Meghalaya', label: 'Meghalaya' },
    { value: 'Mizoram', label: 'Mizoram' },
    { value: 'Nagaland', label: 'Nagaland' },
    { value: 'Odisha', label: 'Odisha' },
    { value: 'Punjab', label: 'Punjab' },
    { value: 'Rajasthan', label: 'Rajasthan' },
    { value: 'Sikkim', label: 'Sikkim' },
    { value: 'Tamil Nadu', label: 'Tamil Nadu' },
    { value: 'Telangana', label: 'Telangana' },
    { value: 'Tripura', label: 'Tripura' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
    { value: 'Uttarakhand', label: 'Uttarakhand' },
    { value: 'West Bengal', label: 'West Bengal' },
  ];
  static readonly Countries = [
    { value: 'Afghanistan', label: 'Afghanistan' },
    { value: 'Albania', label: 'Albania' },
    { value: 'Algeria', label: 'Algeria' },
    { value: 'Andorra', label: 'Andorra' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Armenia', label: 'Armenia' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Azerbaijan', label: 'Azerbaijan' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bahrain', label: 'Bahrain' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Barbados', label: 'Barbados' },
    { value: 'Belarus', label: 'Belarus' },
    { value: 'Belgium', label: 'Belgium' },
    { value: 'Belize', label: 'Belize' },
    { value: 'Benin', label: 'Benin' },
    { value: 'Bhutan', label: 'Bhutan' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'Brazil', label: 'Brazil' },
    { value: 'Brunei', label: 'Brunei' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Cabo Verde', label: 'Cabo Verde' },
    { value: 'Cambodia', label: 'Cambodia' },
    { value: 'Cameroon', label: 'Cameroon' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Central African Republic', label: 'Central African Republic' },
    { value: 'Chad', label: 'Chad' },
    { value: 'Chile', label: 'Chile' },
    { value: 'China', label: 'China' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Comoros', label: 'Comoros' },
    { value: 'Congo (Congo-Brazzaville)', label: 'Congo (Congo-Brazzaville)' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Croatia', label: 'Croatia' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Cyprus', label: 'Cyprus' },
    { value: 'Czechia (Czech Republic)', label: 'Czechia (Czech Republic)' },
    { value: 'Democratic Republic of the Congo', label: 'Democratic Republic of the Congo' },
    { value: 'Denmark', label: 'Denmark' },
    { value: 'Djibouti', label: 'Djibouti' },
    { value: 'Dominica', label: 'Dominica' },
    { value: 'Dominican Republic', label: 'Dominican Republic' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'Egypt', label: 'Egypt' },
    { value: 'El Salvador', label: 'El Salvador' },
    { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
    { value: 'Eritrea', label: 'Eritrea' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Eswatini (fmr. "Swaziland")', label: 'Eswatini (fmr. "Swaziland")' },
    { value: 'Ethiopia', label: 'Ethiopia' },
    { value: 'Fiji', label: 'Fiji' },
    { value: 'Finland', label: 'Finland' },
    { value: 'France', label: 'France' },
    { value: 'Gabon', label: 'Gabon' },
    { value: 'Gambia', label: 'Gambia' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Germany', label: 'Germany' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Greece', label: 'Greece' },
    { value: 'Grenada', label: 'Grenada' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guinea', label: 'Guinea' },
    { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Haiti', label: 'Haiti' },
    { value: 'Holy See', label: 'Holy See' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Hungary', label: 'Hungary' },
    { value: 'Iceland', label: 'Iceland' },
    { value: 'India', label: 'India' },
    { value: 'Indonesia', label: 'Indonesia' },
    { value: 'Iran', label: 'Iran' },
    { value: 'Iraq', label: 'Iraq' },
    { value: 'Ireland', label: 'Ireland' },
    { value: 'Israel', label: 'Israel' },
    { value: 'Italy', label: 'Italy' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Japan', label: 'Japan' },
    { value: 'Jordan', label: 'Jordan' },
    { value: 'Kazakhstan', label: 'Kazakhstan' },
    { value: 'Kenya', label: 'Kenya' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Kuwait', label: 'Kuwait' },
    { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Latvia', label: 'Latvia' },
    { value: 'Lebanon', label: 'Lebanon' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Libya', label: 'Libya' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Lithuania', label: 'Lithuania' },
    { value: 'Luxembourg', label: 'Luxembourg' },
    { value: 'Madagascar', label: 'Madagascar' },
    { value: 'Malawi', label: 'Malawi' },
    { value: 'Malaysia', label: 'Malaysia' },
    { value: 'Maldives', label: 'Maldives' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Marshall Islands', label: 'Marshall Islands' },
    { value: 'Mauritania', label: 'Mauritania' },
    { value: 'Mauritius', label: 'Mauritius' },
    { value: 'Mexico', label: 'Mexico' },
    { value: 'Micronesia', label: 'Micronesia' },
    { value: 'Moldova', label: 'Moldova' },
    { value: 'Monaco', label: 'Monaco' },
    { value: 'Mongolia', label: 'Mongolia' },
    { value: 'Montenegro', label: 'Montenegro' },
    { value: 'Morocco', label: 'Morocco' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Myanmar (formerly Burma)', label: 'Myanmar (formerly Burma)' },
    { value: 'Namibia', label: 'Namibia' },
    { value: 'Nauru', label: 'Nauru' },
    { value: 'Nepal', label: 'Nepal' },
    { value: 'Netherlands', label: 'Netherlands' },
    { value: 'New Zealand', label: 'New Zealand' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Niger', label: 'Niger' },
    { value: 'Nigeria', label: 'Nigeria' },
    { value: 'North Korea', label: 'North Korea' },
    { value: 'North Macedonia', label: 'North Macedonia' },
    { value: 'Norway', label: 'Norway' },
    { value: 'Oman', label: 'Oman' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'Palau', label: 'Palau' },
    { value: 'Palestine State', label: 'Palestine State' },
    { value: 'Panama', label: 'Panama' },
    { value: 'Papua New Guinea', label: 'Papua New Guinea' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Peru', label: 'Peru' },
    { value: 'Philippines', label: 'Philippines' },
    { value: 'Poland', label: 'Poland' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Qatar', label: 'Qatar' },
    { value: 'Romania', label: 'Romania' },
    { value: 'Russia', label: 'Russia' },
    { value: 'Rwanda', label: 'Rwanda' },
    { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
    { value: 'Saint Lucia', label: 'Saint Lucia' },
    { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'San Marino', label: 'San Marino' },
    { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
    { value: 'Saudi Arabia', label: 'Saudi Arabia' },
    { value: 'Senegal', label: 'Senegal' },
    { value: 'Serbia', label: 'Serbia' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Sierra Leone', label: 'Sierra Leone' },
    { value: 'Singapore', label: 'Singapore' },
    { value: 'Slovakia', label: 'Slovakia' },
    { value: 'Slovenia', label: 'Slovenia' },
    { value: 'Solomon Islands', label: 'Solomon Islands' },
    { value: 'Somalia', label: 'Somalia' },
    { value: 'South Africa', label: 'South Africa' },
    { value: 'South Korea', label: 'South Korea' },
    { value: 'South Sudan', label: 'South Sudan' },
    { value: 'Spain', label: 'Spain' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Sudan', label: 'Sudan' },
    { value: 'Suriname', label: 'Suriname' },
    { value: 'Sweden', label: 'Sweden' },
    { value: 'Switzerland', label: 'Switzerland' },
    { value: 'Syria', label: 'Syria' },
    { value: 'Tajikistan', label: 'Tajikistan' },
    { value: 'Tanzania', label: 'Tanzania' },
    { value: 'Thailand', label: 'Thailand' },
    { value: 'Timor-Leste', label: 'Timor-Leste' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Tonga', label: 'Tonga' },
    { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
    { value: 'Tunisia', label: 'Tunisia' },
    { value: 'Turkey', label: 'Turkey' },
    { value: 'Turkmenistan', label: 'Turkmenistan' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Ukraine', label: 'Ukraine' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates' },
    { value: 'United Kingdom', label: 'United Kingdom' },
    { value: 'United States of America', label: 'United States of America' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Uzbekistan', label: 'Uzbekistan' },
    { value: 'Vanuatu', label: 'Vanuatu' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'Yemen', label: 'Yemen' },
    { value: 'Zambia', label: 'Zambia' },
    { value: 'Zimbabwe', label: 'Zimbabwe' },
  ];
  static readonly Languages = [
    { value: 'Hindi', label: 'Hindi' },
    { value: 'English', label: 'English' },
    { value: 'Bengali', label: 'Bengali' },
    { value: 'Marathi', label: 'Marathi' },
    { value: 'Telugu', label: 'Telugu' },
    { value: 'Tamil', label: 'Tamil' },
    { value: 'Gujarati', label: 'Gujarati' },
    { value: 'Urdu', label: 'Urdu' },
    { value: 'Kannada', label: 'Kannada' },
    { value: 'Odia', label: 'Odia' },
    { value: 'Malayalam', label: 'Malayalam' },
    { value: 'Punjabi', label: 'Punjabi' },
    { value: 'Assamese', label: 'Assamese' },
    { value: 'Maithili', label: 'Maithili' },
    { value: 'Sanskrit', label: 'Sanskrit' },
    { value: 'Other', label: 'Other' },
  ];
  static readonly Raasi = [
    { value: 'Aries', label: 'Aries(మేషము)' },
    { value: 'Taurus', label: 'Taurus(వృషభము)' },
    { value: 'Gemini', label: 'Gemini(మిథునము)' },
    { value: 'Cancer', label: 'Cancer(కర్కాటకము)' },
    { value: 'Leo', label: 'Leo(సింహము)' },
    { value: 'Virgo', label: 'Virgo(కన్యా)' },
    { value: 'Libra', label: 'Libra(తుల)' },
    { value: 'Scorpio', label: 'Scorpio(వృశ్చికము)' },
    { value: 'Saggitarius', label: 'Saggitarius(ధనస్సు)' },
    { value: 'Capricorn', label: 'Capricorn(మకరము)' },
    { value: 'Aquarius', label: 'Aquarius(కుంభము)' },
    { value: 'Pisces', label: 'Pisces(మీనము)' },
    { value: 'Not', label: 'Not preffered' },
  ];
  static readonly Caste = [
    { value: 'Achukatlavandlu', label: 'Achukatlavandlu' },
    { value: 'Agaru', label: 'Agaru' },
    { value: 'Agnikulakshatriya', label: 'Agnikulakshatriya' },
    { value: 'Arekatika', label: 'Arekatika' },
    { value: 'Aryakshatriy', label: 'Aryakshatriy' },
    { value: 'Atagara', label: 'Atagara' },
    { value: 'Atirasa', label: 'Atirasa' },
    { value: 'Ayyaraka', label: 'Ayyaraka' },
    { value: 'Balasanthu', label: 'Balasanthu' },
    { value: 'Balija', label: 'Balija' },
    { value: 'Bandara', label: 'Bandara' },
    { value: 'Bestha', label: 'Bestha' },
    { value: 'Bhataraju', label: 'Bhataraju' },
    { value: 'Budabukkala', label: 'Budabukkala' },
    { value: 'Budubunjala', label: 'Budubunjala' },
    { value: 'Chippolu (Mera)', label: 'Chippolu (Mera)' },
    { value: 'Chopemari', label: 'Chopemari' },
    { value: 'Dasari', label: 'Dasari' },
    { value: 'Devanga', label: 'Devanga' },
    { value: 'Dommara', label: 'Dommara' },
    { value: 'Dudekula', label: 'Dudekula' },
    { value: 'Ediga Gowda', label: 'Ediga Gowda' },
    { value: 'Gajula Balija', label: 'Gajula Balija' },
    { value: 'Gandla', label: 'Gandla' },
    { value: 'Gangaputra', label: 'Gangaputra' },
    { value: 'Gangavar', label: 'Gangavar' },
    { value: 'Gangiredlavaru', label: 'Gangiredlavaru' },
    { value: 'Gavara', label: 'Gavara' },
    { value: 'Godaba', label: 'Godaba' },
    { value: 'Golla (Yadava)', label: 'Golla (Yadava)' },
    { value: 'Goondla', label: 'Goondla' },
    { value: 'Goud', label: 'Goud' },
    { value: 'Gudala', label: 'Gudala' },
    { value: 'Gudia/Gudiya', label: 'Gudia/Gudiya' },
    { value: 'Hatkar', label: 'Hatkar' },
    { value: 'Jakkala', label: 'Jakkala' },
    { value: 'Jalari', label: 'Jalari' },
    { value: 'Jandra', label: 'Jandra' },
    { value: 'Jangam', label: 'Jangam' },
    { value: 'Jingar', label: 'Jingar' },
    { value: 'Jogi', label: 'Jogi' },
    { value: 'Joshinandiwala', label: 'Joshinandiwala' },
    { value: 'Kachi', label: 'Kachi' },
    { value: 'Kaikadi', label: 'Kaikadi' },
    { value: 'Kandra', label: 'Kandra' },
    { value: 'Kanjara-Bhatta', label: 'Kanjara-Bhatta' },
    { value: 'Karikalabhakthulu', label: 'Karikalabhakthulu' },
    { value: 'Karnabhakthulu', label: 'Karnabhakthulu' },
    { value: 'Kasi kapadi', label: 'Kasi kapadi' },
    { value: 'Katipapala', label: 'Katipapala' },
    { value: 'Kepmare or Reddika', label: 'Kepmare or Reddika' },
    { value: 'Kinthala Kalinga', label: 'Kinthala Kalinga' },
    { value: 'Koppulavelama', label: 'Koppulavelama' },
    { value: 'Korcha, Koracha', label: 'Korcha, Koracha' },
    { value: 'Koshti', label: 'Koshti' },
    { value: 'Krishnabhalija', label: 'Krishnabhalija' },
    { value: 'Kummara', label: 'Kummara' },
    { value: 'Kunapuli', label: 'Kunapuli' },
    { value: 'Kurakula', label: 'Kurakula' },
    { value: 'Kurm', label: 'Kurm' },
    { value: 'Kuruba', label: 'Kuruba' },
    { value: 'Lakkamari Kapu', label: 'Lakkamari Kapu' },
    { value: 'Lodh', label: 'Lodh' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Mandula', label: 'Mandula' },
    { value: 'Mathura', label: 'Mathura' },
    { value: 'Medari or Mahendra', label: 'Medari or Mahendra' },
    { value: 'Mehtar (Muslim)', label: 'Mehtar (Muslim)' },
    { value: 'Mondepatta Mondipatta', label: 'Mondepatta Mondipatta' },
    { value: 'Mondivaru Mondibanda Banda', label: 'Mondivaru Mondibanda Banda' },
    { value: 'Mudiraj', label: 'Mudiraj' },
    { value: 'Munnurukapu', label: 'Munnurukapu' },
    { value: 'Nagaralu', label: 'Nagaralu' },
    { value: 'Nagavaddilu', label: 'Nagavaddilu' },
    { value: 'Nagavasam (Nagavamsa)', label: 'Nagavasam (Nagavamsa)' },
    { value: 'Nayi-Brahmin', label: 'Nayi-Brahmin' },
    { value: 'Nayyala', label: 'Nayyala' },
    { value: 'Neelakanthi', label: 'Neelakanthi' },
    { value: 'Neeli (Nelli)', label: 'Neeli (Nelli)' },
    { value: 'Nessi or Kurni', label: 'Nessi or Kurni' },
    { value: 'Nokkar', label: 'Nokkar' },
    { value: 'Odde', label: 'Odde' },
    { value: 'Padmasali', label: 'Padmasali' },
    { value: 'Pala-Ekari', label: 'Pala-Ekari' },
    { value: 'Palli', label: 'Palli' },
    { value: 'Pallikapu', label: 'Pallikapu' },
    { value: 'Pallireddi', label: 'Pallireddi' },
    { value: 'Pambala', label: 'Pambala' },
    { value: 'Pamula', label: 'Pamula' },
    { value: 'Pardhi', label: 'Pardhi' },
    { value: 'Pariki Muggula', label: 'Pariki Muggula' },
    { value: 'Passi', label: 'Passi' },
    { value: 'Patkar', label: 'Patkar' },
    { value: 'Patra', label: 'Patra' },
    { value: 'Pattapu', label: 'Pattapu' },
    { value: 'Peddammavandlu', label: 'Peddammavandlu' },
    { value: 'Perika', label: 'Perika' },
    { value: 'Pollinativelama', label: 'Pollinativelama' },
    { value: 'Pondara', label: 'Pondara' },
    { value: 'Poosala', label: 'Poosala' },
    { value: 'Rajaka', label: 'Rajaka' },
    { value: 'Rangarez', label: 'Rangarez' },
    { value: 'Sadhuchetty', label: 'Sadhuchetty' },
    { value: 'Sarollu', label: 'Sarollu' },
    { value: 'Satani', label: 'Satani' },
    { value: 'Siddula', label: 'Siddula' },
    { value: 'Sikligar', label: 'Sikligar' },
    { value: 'Srisayana', label: 'Srisayana' },
    { value: 'Surya Balija', label: 'Surya Balija' },
    { value: 'Swakulasali', label: 'Swakulasali' },
    { value: 'Tammali', label: 'Tammali' },
    { value: 'Telaga', label: 'Telaga' },
    { value: 'Thogata', label: 'Thogata' },
    { value: 'Turupu Kapu', label: 'Turupu Kapu' },
    { value: 'Uppara or Sagara', label: 'Uppara or Sagara' },
    { value: 'Vadabalija', label: 'Vadabalija' },
    { value: 'Valmiki Boya', label: 'Valmiki Boya' },
    { value: 'Vamsha Raj', label: 'Vamsha Raj' },
    { value: 'Vanjara (Vanjari)', label: 'Vanjara (Vanjari)' },
    { value: 'Vannekapu', label: 'Vannekapu' },
    { value: 'Vannereddi', label: 'Vannereddi' },
    { value: 'Vannia Vanniar Vannikula-Kshatriya', label: 'Vannia Vanniar Vannikula-Kshatriya' },
    { value: 'Vanyakulakshtriya', label: 'Vanyakulakshtriya' },
    { value: 'Veeramushti', label: 'Veeramushti' },
    { value: 'Viswabrahmin', label: 'Viswabrahmin' },
    { value: 'Yata', label: 'Yata' },
  ];
  static readonly Occupation = [
    { value: 'Accountant', label: 'Accountant' },
    { value: 'Administrative', label: 'Administrative' },
    { value: 'Advertising', label: 'Advertising' },
    { value: 'Agriculture', label: 'Agriculture' },
    { value: 'Animator', label: 'Animator' },
    { value: 'Architect', label: 'Architect' },
    { value: 'Artist', label: 'Artist' },
    { value: 'Attorney', label: 'Attorney' },
    { value: 'Banking Services', label: 'Banking Services' },
    { value: 'Business', label: 'Business' },
    { value: 'Captain', label: 'Captain' },
    { value: 'Chartered Accountant', label: 'Chartered Accountant' },
    { value: 'Chemist', label: 'Chemist' },
    { value: 'Clerical', label: 'Clerical' },
    { value: 'Clinical Research Associate', label: 'Clinical Research Associate' },
    { value: 'Commercial Pilot', label: 'Commercial Pilot' },
    { value: 'Consultant', label: 'Consultant' },
    { value: 'Contractor', label: 'Contractor' },
    { value: 'Counselor', label: 'Counselor' },
    { value: 'Customer Support', label: 'Customer Support' },
    { value: 'Defense Services', label: 'Defense Services' },
    { value: 'Dentist', label: 'Dentist' },
    { value: 'Director', label: 'Director' },
    { value: 'Doctor', label: 'Doctor' },
    { value: 'Editor', label: 'Editor' },
    { value: 'Engineer', label: 'Engineer' },
    { value: 'Executive', label: 'Executive' },
    { value: 'Farming', label: 'Farming' },
    { value: 'Fashion Designer', label: 'Fashion Designer' },
    { value: 'Govt Employee', label: 'Govt Employee' },
    { value: 'Hardware Professional', label: 'Hardware Professional' },
    { value: 'Homemaker', label: 'Homemaker' },
    { value: 'Insurance Agent', label: 'Insurance Agent' },
    { value: 'Interior Designer', label: 'Interior Designer' },
    { value: 'Journalist', label: 'Journalist' },
    { value: 'Law Enforcement', label: 'Law Enforcement' },
    { value: 'Lawyer', label: 'Lawyer' },
    { value: 'Lecturer', label: 'Lecturer' },
    { value: 'Librarian', label: 'Librarian' },
    { value: 'Management', label: 'Management' },
    { value: 'Manager', label: 'Manager' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Medical Assistant', label: 'Medical Assistant' },
    { value: 'Medical Representative', label: 'Medical Representative' },
    { value: 'Medical Services', label: 'Medical Services' },
    { value: 'Medical Transcription', label: 'Medical Transcription' },
    { value: 'MicroBiologist', label: 'MicroBiologist' },
    { value: 'Nurse', label: 'Nurse' },
    { value: 'Occupational Therapist', label: 'Occupational Therapist' },
    { value: 'Optician', label: 'Optician' },
    { value: 'Pharmacist', label: 'Pharmacist' },
    { value: 'Physician', label: 'Physician' },
    { value: 'Physiotherapist', label: 'Physiotherapist' },
    { value: 'Pilot', label: 'Pilot' },
    { value: 'President', label: 'President' },
    { value: 'Principal', label: 'Principal' },
    { value: 'Professor', label: 'Professor' },
    { value: 'Programmer', label: 'Programmer' },
    { value: 'Psychologist', label: 'Psychologist' },
    { value: 'Public Relations', label: 'Public Relations' },
    { value: 'Real Estate', label: 'Real Estate' },
    { value: 'Receptionist', label: 'Receptionist' },
    { value: 'Registrar', label: 'Registrar' },
    { value: 'Research Scholar', label: 'Research Scholar' },
    { value: 'Retired', label: 'Retired' },
    { value: 'Sales', label: 'Sales' },
    { value: 'Scientist', label: 'Scientist' },
    { value: 'Self Employed', label: 'Self Employed' },
    { value: 'Senior Associate', label: 'Senior Associate' },
    { value: 'Senior Associate', label: 'Senior Associate' },
    { value: 'Social Sciences', label: 'Social Sciences' },
    { value: 'Social Worker', label: 'Social Worker' },
    { value: 'Software Professional', label: 'Software Professional' },
    { value: 'Student', label: 'Student' },
    { value: 'Supervisor', label: 'Supervisor' },
    { value: 'Systems Analyst', label: 'Systems Analyst' },
    { value: 'Teacher', label: 'Teacher' },
    { value: 'Technical Manager', label: 'Technical Manager' },
    { value: 'Technician', label: 'Technician' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'Translator', label: 'Translator' },
    { value: 'Volunteer', label: 'Volunteer' },
    { value: 'Writer', label: 'Writer' },
    { value: 'Other', label: 'Other' },
  ];
  static readonly Filledby = [
    { value: '1', label: 'Self' },
    { value: '2', label: 'Parent' },
    { value: '3', label: 'Sibling' },
    { value: '4', label: 'Relative/Guardian' },
    { value: '5', label: 'Friend' },
    { value: '6', label: 'Other' }];
  static readonly Religous = [
    { value: 'Hindu', label: 'Hindu' },
    { value: 'Muslim', label: 'Muslim' },
    { value: 'Christian', label: 'Christian' },
    { value: 'Buddhist', label: 'Buddhist' },
    { value: 'Sikh', label: 'Sikh' },
    { value: 'Atheist', label: 'Atheist' },
    { value: 'Jain', label: 'Jain' },
    { value: 'Catholic', label: 'Catholic' },
    { value: 'Jew', label: 'Jew' },
    { value: 'Parsi', label: 'Parsi' },
    { value: 'Protestant', label: 'Protestant' },
    { value: 'Other', label: 'Other' }];
}
